### ISSUE TITLE
Azure Function : Write a message to Topic from function

### ISSUE THREAD

**Issue by arunprasathv** [damienbod/AspNetCoreServiceBus#6]
Do you have a sample that writes a message to a service bus topic from azure function? reading connection string values from key vault.

**Comment by damienbod** [comment]
Hi @arunprasathv not public,  will add something like this . You would basically do something like this:

https://damienbod.com/2020/07/20/using-key-vault-and-managed-identities-with-azure-functions/

then read the bus connection string in. 

Greetings Damien

**Comment by arunprasathv** [comment]
Great, So the connection string will have only base key vault URI, and  not for every secret. now i can store multiple keys. How to manage the keys between multiple environments. i want to use one KV for all non-prod. I will have separate SB for every env.

**Comment by arunprasathv** [comment]
Mine is not a durable function, can i still use startup class ? i'm using Function App.

**Comment by arunprasathv** [comment]
also i dont see anywhere in your code keyvault end point is being used.  I see this line 
                var keyVaultClient = new KeyVaultClient(new KeyVaultClient.AuthenticationCallback(azureServiceTokenProvider.KeyVaultTokenCallback));

but not being used anywhere.

**Comment by arunprasathv** [comment]
also i want to use this in my Function which is a static class. I can't do  
        private readonly MyConfigurationSecrets _myConfigurationSecrets;

**Comment by damienbod** [comment]
updated and fixed
